Series Object
-------------
Series is One-dimensional labelled array for homogenous data.

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.Series()

<ipython-input-2-fa15c544da3b>:1: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  pd.Series()

Series([], dtype: float64)

In [3]:
icecream_flavors = ["vanilla","Butterscotch","Strawberry","Chocolate"]
pd.Series(icecream_flavors)

0         vanilla
1    Butterscotch
2      Strawberry
3       Chocolate
dtype: object

In [4]:
pd.Series(
    data = None,
    index=None,
    dtype=None,
    name=None,
    name=None,
    copy=False,
    fastpath=None
)

SyntaxError: keyword argument repeated (<ipython-input-4-daee4eefb285>, line 6)

In [ ]:
icecream_flavors = ["vanilla","Butterscotch","Strawberry","Chocolate"]
days_of_week = ("Monday","Wednesday","Thursday","Saturday")
pd.Series(icecream_flavors,index=days_of_week)

Monday            vanilla
Wednesday    Butterscotch
Thursday       Strawberry
Saturday        Chocolate
dtype: object

In [ ]:
#create a Series oobject with gold prices and days_of_week
days_of_week = ("Monday","Wednesday","Thursday","Saturday")
prices_of_week=[46600,46700,46800,46900]
pd.Series(data=prices_of_week,index=days_of_week)

Monday       46600
Wednesday    46700
Thursday     46800
Saturday     46900
dtype: int64

In [ ]:
# Creating a series from a python dictionary
calorie_info = {
    'Rice':136,
    'Chapathi':79,
    'dal':104
}
diet =pd.Series(calorie_info)
print(diet)

Rice        136
Chapathi     79
dal         104
dtype: int64

In [ ]:
recent_movies = {'Vikram','Thor','Major','Viratparvam'}
movies=pd.Series(list(recent_movies))
print(movies)

0    Viratparvam
1           Thor
2         Vikram
3          Major
dtype: object

In [ ]:
print(movies.values)
print(type(movies.values))
print(movies.size)
print(movies.shape)
print(movies.head(2))
print(movies.tail(2))
diet+1

['Viratparvam' 'Thor' 'Vikram' 'Major']
<class 'numpy.ndarray'>
4
(4,)
0    Viratparvam
1           Thor
dtype: object
2    Vikram
3     Major
dtype: object

Rice        137
Chapathi     80
dal         105
dtype: int64

In [ ]:
pd.Series(data=["Admin","architect","tester","developer"]).sort_values()

0        Admin
1    architect
3    developer
2       tester
dtype: object

In [ ]:
pd.Series(data=["Admin","architect","tester","developer"]).sort_values(ascending=False)

2       tester
3    developer
1    architect
0        Admin
dtype: object

In [ ]:
netflix_titles = pd.read_csv(filepath_or_buffer=r'netflix_titles.csv',index_col='show_id',parse_dates=['date_added'])
print(netflix_titles.sort_values(ascending=False,by='date_added').head(5))

            type                                title  \
show_id
s1         Movie                 Dick Johnson Is Dead
s7         Movie     My Little Pony: A New Generation
s11      TV Show  Vendetta: Truth, Lies and The Mafia
s10        Movie                         The Starling
s9       TV Show        The Great British Baking Show

                              director  \
show_id
s1                     Kirsten Johnson
s7       Robert Cullen, Jos√© Luis Ucha
s11                                NaN
s10                     Theodore Melfi
s9                     Andy Devonshire

                                                      cast         country  \
show_id
s1                                                     NaN   United States
s7       Vanessa Hudgens, Kimiko Glenn, James Marsden, ...             NaN
s11                                                    NaN             NaN
s10      Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...   United States
s9       Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...  United Kingdom

        date_added  release_year rating   duration  \
show_id
s1      2021-09-25          2020  PG-13     90 min
s7      2021-09-24          2021     PG     91 min
s11     2021-09-24          2021  TV-MA   1 Season
s10     2021-09-24          2021  PG-13    104 min
s9      2021-09-24          2021  TV-14  9 Seasons

                                                 listed_in  \
show_id
s1                                           Documentaries
s7                                Children & Family Movies
s11      Crime TV Shows, Docuseries, International TV S...
s10                                       Comedies, Dramas
s9                            British TV Shows, Reality TV

                                               description
show_id
s1       As her father nears the end of his life, filmm...
s7       Equestria's divided. But a bright-eyed hero be...
s11      Sicily boasts a bold "Anti-Mafia" coalition. B...
s10      A woman adjusting to life after a loss contend...
s9       A talented batch of amateur bakers face off in...

In [ ]:
netflix_titles.dropna(inplace=True)
netflix_titles.sort_values(ascending=False,by='date_added').head()

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...",2021-09-24,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,2021-09-24,2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,2021-09-24,2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niew√∂hner, Milan Peschel, ...","Germany, Czech Republic",2021-09-23,2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,2021-09-21,1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...

In [ ]:
# finding smallest and largest values
movies = netflix_titles.sort_values(ascending=False,by='release_year')

#largest values or latest movies
print(movies.head())

#smallest values or oldest movies
print(movies.tail())

            type                title  \
show_id
s1185      Movie  The Yin Yang Master
s911       Movie              Monster
s298     TV Show             Navarasa
s300       Movie            The Swarm
s301       Movie                 Vivo

                                                  director  \
show_id
s1185                                            Li Weiran
s911                                       Anthony Mandler
s298     Bejoy Nambiar, Priyadarshan, Karthik Narain, V...
s300                                        Just Philippot
s301                        Kirk DeMicco, Brandon Jeffords

                                                      cast  \
show_id
s1185    Chen Kun, Zhou Xun, Qu Chuxiao, Shen Yue, Will...
s911     Kelvin Harrison Jr., Jennifer Hudson, Jeffrey ...
s298     Suriya, Vijay Sethupathi, Revathy, Prakash Raj...
s300     Suliane Brahim, Sofian Khammes, Marie Narbonne...
s301     Lin-Manuel Miranda, Ynairaly Simo, Zoe Saldana...

                       country date_added  release_year rating  duration  \
show_id
s1185                    China 2021-03-19          2021  TV-14   120 min
s911             United States 2021-05-07          2021  TV-MA    99 min
s298                     India 2021-08-06          2021  TV-MA  1 Season
s300                    France 2021-08-06          2021  TV-14   102 min
s301     Canada, United States 2021-08-06          2021     PG   100 min

                                                 listed_in  \
show_id
s1185             Action & Adventure, International Movies
s911                                                Dramas
s298                                              TV Shows
s300     Horror Movies, Independent Movies, Internation...
s301            Children & Family Movies, Music & Musicals

                                               description
show_id
s1185    A feud erupts between realms, and Yin Yang mas...
s911     A talented teen implicated in a robbery-turned...
s298     From amusement to awe, the nine human emotions...
s300     A single mother breeds locusts as high-protein...
s301     A music-loving kinkajou embarks on the journey...
          type                    title  \
show_id
s8588    Movie              Thunderbolt
s7295    Movie       Let There Be Light
s7220    Movie  Know Your Enemy - Japan
s8641    Movie         Tunisian Victory
s8206    Movie     The Battle of Midway

                                                  director  \
show_id
s8588                          William Wyler, John Sturges
s7295                                          John Huston
s7220                             Frank Capra, Joris Ivens
s8641    Frank Capra, John Huston, Hugh Stewart, Roy Bo...
s8206                                            John Ford

                                 cast                        country  \
show_id
s8588    James Stewart, Lloyd Bridges                  United States
s7295                   Walter Huston                  United States
s7220     Walter Huston, Dana Andrews                  United States
s8641                Burgess Meredith  United States, United Kingdom
s8206       Henry Fonda, Jane Darwell                  United States

        date_added  release_year rating duration  \
show_id
s8588   2017-03-31          1947  TV-PG   42 min
s7295   2017-03-31          1946  TV-PG   58 min
s7220   2017-03-31          1945  TV-14   63 min
s8641   2017-03-31          1944  TV-14   76 min
s8206   2017-03-31          1942  TV-14   18 min

                             listed_in  \
show_id
s8588    Classic Movies, Documentaries
s7295    Classic Movies, Documentaries
s7220    Classic Movies, Documentaries
s8641    Classic Movies, Documentaries
s8206    Classic Movies, Documentaries

                                               description
show_id
s8588    A P-47 Thunderbolt squadron is shown in prepar...
s7295    Some returning combat veterans suffer scars th...
s7220    Though culturally insensitive by modern standa...
s8641    British and American troops join forces to lib...
s8206    Director John Ford captures combat footage of ...

In [ ]:
print(type(netflix_titles['country']))
print(netflix_titles['country'].value_counts())

<class 'pandas.core.series.Series'>
United States                                    1846
India                                             875
United Kingdom                                    183
Canada                                            107
Spain                                              91
                                                 ...
Ireland, South Africa                               1
United Kingdom, Russia, United States               1
United States, France, Canada, Lebanon, Qatar       1
Italy, Switzerland, Albania, Poland                 1
Australia, United Kingdom, Canada                   1
Name: country, Length: 604, dtype: int64

In [ ]:
netflix_titles['release_year'].value_counts(bins=6,sort=False)

(1941.92, 1955.167]       10
(1955.167, 1968.333]      26
(1968.333, 1981.5]        86
(1981.5, 1994.667]       184
(1994.667, 2007.833]     574
(2007.833, 2021.0]      4452
Name: release_year, dtype: int64

In [ ]:
# Create a __DataFrame__ with city, state, country and population as columns and insert some data in city_data
city_data= {
    "City" : ["Mumbai","Delhi","Bengaluru","Hyderabad"],
    "State" : ["Maharastra","Delhi","Karnataka","Telangana"],
    "Population" : [12691836,10927986,8443675,6809970]
}
cities=pd.DataFrame(data=city_data)
cities

        City       State  Population
0     Mumbai  Maharastra    12691836
1      Delhi       Delhi    10927986
2  Bengaluru   Karnataka     8443675
3  Hyderabad   Telangana     6809970

Filtering a DataFrame
----------------------

In [9]:
netflix_titles = pd.read_csv(r'netflix_titles.csv')
netflix_titles.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [12]:
netflix_titles = pd.read_csv(r'netflix_titles.csv',parse_dates=['date_added'])
netflix_titles.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [13]:
netflix_titles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   datetime64[ns]
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: datetime64[ns](1), int64(1), object(10)
memory usage: 825.8+ KB

In [11]:
# Fill NaN values
netflix_titles["country"].fillna('United States',inplace=True)
netflix_titles.tail(6)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8801,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,United States,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [14]:
netflix_titles = pd.read_csv(r'netflix_titles.csv',parse_dates=['date_added'])
netflix_titles.nunique()

show_id         8807
type               2
title           8807
director        4528
cast            7692
country          748
date_added      1714
release_year      74
rating            17
duration         220
listed_in        514
description     8775
dtype: int64

In [15]:
#lets categorize the data
netflix_titles['type'].astype('category')

0         Movie
1       TV Show
2       TV Show
3       TV Show
4       TV Show
         ...
8802      Movie
8803    TV Show
8804      Movie
8805      Movie
8806      Movie
Name: type, Length: 8807, dtype: category
Categories (2, object): ['Movie', 'TV Show']

In [18]:
#filter by release year
netflix_titles[netflix_titles['release_year']==2021]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,2021-09-24,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
...,...,...,...,...,...,...,...,...,...,...,...,...
1468,s1469,Movie,What Happened to Mr. Cha?,Kim Dong-kyu,"Cha In-pyo, Cho Dal-hwan, Song Jae-ryong",South Korea,2021-01-01,2021,TV-MA,102 min,"Comedies, International Movies","With the peak of his career long behind him, a..."
1551,s1552,TV Show,Hilda,NaN,"Bella Ramsey, Ameerah Falzon-Ojo, Oliver Nelso...","United Kingdom, Canada, United States",2020-12-14,2021,TV-Y7,2 Seasons,Kids' TV,"Fearless, free-spirited Hilda finds new friend..."
1696,s1697,TV Show,Polly Pocket,NaN,"Emily Tennant, Shannon Chan-Kent, Kazumi Evans...","Canada, United States, Ireland",2020-11-15,2021,TV-Y,2 Seasons,Kids' TV,After uncovering a magical locket that allows ...
2920,s2921,TV Show,Love Is Blind,NaN,"Nick Lachey, Vanessa Lachey",United States,2020-02-13,2021,TV-MA,1 Season,"Reality TV, Romantic TV Shows",Nick and Vanessa Lachey host this social exper...
8437,s8438,TV Show,The Netflix Afterparty,NaN,"David Spade, London Hughes, Fortune Feimster",United States,2021-01-02,2021,TV-MA,1 Season,"Stand-Up Comedy & Talk Shows, TV Comedies","Hosts David Spade, Fortune Feimster and London..."

In [21]:
#inversion with ~
my_series= pd.Series([True,False,True])
print(my_series)
print('inverted_series')
print(~my_series)

#lets apply this
is_indian = netflix_titles['country']=="India"
netflix_titles[~is_indian].head(3)

0     True
1    False
2     True
dtype: bool
inverted_series
0    False
1     True
2    False
dtype: bool

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...

In [24]:
# isin
is_american = netflix_titles['country']=="United States"
is_indian = netflix_titles['country']=="India"
print(netflix_titles[is_american|is_indian].head())
print('#'*100)
countries = ["India","United States"]
is_titles_in_countries = netflix_titles['country'].isin(countries)
netflix_titles[is_titles_in_countries]

   show_id     type                 title         director  \
0       s1    Movie  Dick Johnson Is Dead  Kirsten Johnson
4       s5  TV Show          Kota Factory              NaN
9      s10    Movie          The Starling   Theodore Melfi
15     s16  TV Show     Dear White People              NaN
24     s25    Movie                 Jeans       S. Shankar

                                                 cast        country  \
0                                                 NaN  United States
4   Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India
9   Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...  United States
15  Logan Browning, Brandon P. Bell, DeRon Horton,...  United States
24  Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...          India

   date_added  release_year rating   duration  \
0  2021-09-25          2020  PG-13     90 min
4  2021-09-24          2021  TV-MA  2 Seasons
9  2021-09-24          2021  PG-13    104 min
15 2021-09-22          2021  TV-MA  4 Seasons
24 2021-09-21          1998  TV-14    166 min

                                            listed_in  \
0                                       Documentaries
4   International TV Shows, Romantic TV Shows, TV ...
9                                    Comedies, Dramas
15                             TV Comedies, TV Dramas
24    Comedies, International Movies, Romantic Movies

                                          description
0   As her father nears the end of his life, filmm...
4   In a city of coaching centers known to train I...
9   A woman adjusting to life after a loss contend...
15  Students of color navigate the daily slights a...
24  When the father of the man she loves insists t...
####################################################################################################

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,2021-09-24,2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
15,s16,TV Show,Dear White People,NaN,"Logan Browning, Brandon P. Bell, DeRon Horton,...",United States,2021-09-22,2021,TV-MA,4 Seasons,"TV Comedies, TV Dramas",Students of color navigate the daily slights a...
24,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,2021-09-21,1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...
...,...,...,...,...,...,...,...,...,...,...,...,...
8799,s8800,Movie,Zenda,Avadhoot Gupte,"Santosh Juvekar, Siddharth Chandekar, Sachit P...",India,2018-02-15,2009,TV-14,120 min,"Dramas, International Movies",A change in the leadership of a political part...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,2019-11-20,2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,2019-11-01,2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,2020-01-11,2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2019-03-02,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [32]:
#between
#write an expression to find all the titles between and 1990 and 2000
post_1990 = netflix_titles['release_year']>1990  
before_2000 = netflix_titles['release_year']<2000
# netflix_titles[post_1990 & before_2000].head(10)
between_1999_and_2000 = netflix_titles['release_year'].between(left=1990,right=2000)
netflix_titles[between_1999_and_2000].head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...",2021-09-24,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
22,s23,Movie,Avvai Shanmughi,K.S. Ravikumar,"Kamal Hassan, Meena, Gemini Ganesan, Heera Raj...",NaN,2021-09-21,1996,TV-PG,161 min,"Comedies, International Movies",Newly divorced and denied visitation rights wi...
24,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,2021-09-21,1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...
26,s27,Movie,Minsara Kanavu,Rajiv Menon,"Arvind Swamy, Kajol, Prabhu Deva, Nassar, S.P....",NaN,2021-09-21,1997,TV-PG,147 min,"Comedies, International Movies, Music & Musicals",A tangled love triangle ensues when a man fall...
67,s68,TV Show,Saved by the Bell,NaN,"Mark-Paul Gosselaar, Tiffani Thiessen, Mario L...",United States,2021-09-15,1994,TV-PG,9 Seasons,"Kids' TV, TV Comedies","From middle school to college, best friends Za..."

In [47]:
#Find the null values in countries
#Find countries,cast and directors which are not null
is_country_null = netflix_titles['country'].isnull()
is_cast_null = netflix_titles['cast'].isnull()
director_not_null = netflix_titles['director'].notnull()
netflix_titles[~is_country_null & ~is_cast_null & director_not_null].head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...",2021-09-24,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,2021-09-24,2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,2021-09-24,2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niew√∂hner, Milan Peschel, ...","Germany, Czech Republic",2021-09-23,2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
24,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,2021-09-21,1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...

In [54]:
netflix_titles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   datetime64[ns]
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: datetime64[ns](1), int64(1), object(10)
memory usage: 825.8+ KB

In [57]:
#Dealing with duplicates
is_duplicated = netflix_titles['country'].duplicated()
netflix_titles[is_duplicated]

#drop duplicates in listed_in
netflix_titles.drop_duplicates(subset=['listed_in'],keep='first')

#drop duplicates in description
netflix_titles.drop_duplicates(subset=['description'],keep='last')

#drop duplicates in date_added
netflix_titles.drop_duplicates(subset=['date_added'],keep='last')

#drop duplicates with titles
netflix_titles.drop_duplicates(subset=['title'],keep='first')

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,2019-11-20,2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,2019-07-01,2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,2019-11-01,2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,2020-01-11,2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2019-03-02,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...